version: '3.7'

services:
  model:
    build: ./Backend
    container_name: model
    expose:
      - 5000
    ports:
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    container_name: web
    expose:
      - 5001
    ports:
      - "5001:5000"

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    expose:
      - 8081
    ports:
      - "8005:8081"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    depends_on:
      - web
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - '9091:9091'
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.listen-address=alertmanager:9091'
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
