version : '3.7'


services:
  model:
    build: ./Backend
    container_name: model
    ports: 
      - "5000:5000"

  web:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    container_name: web
    ports:
      - "5001:5000"
    
